kind = "api"
previewPath = "/"
title = "JobBot India"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "JobBot India"
paths = ["/"]

[services.development]
run = "python3 ../../app.py"

[services.production]

[services.production.build]
args = ["python3", "-m", "compileall", "../../app.py", "../../models.py", "../../scrapers", "../../autofill"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["python3", "../../app.py"]

[services.production.run.env]
PORT = "5000"

[services.production.health.startup]
path = "/"
